import {
  FiCheckSquare,
  FiCloud,
  FiCode,
  FiCpu,
  FiCrop,
  FiFileText,
  FiFilm,
  FiGlobe,
  FiGrid,
  FiImage,
  FiMessageCircle,
  FiShield,
  FiTarget,
  FiTool,
  FiUsers,
} from "react-icons/fi";

export const CATEGORY_SLUGS = Object.freeze([
  "all",
  "browser",
  "development",
  "documents",
  "communication",
  "utilities",
  "security",
  "productivity",
  "cloud_storage",
  "collaboration",
  "entertainment",
  "photo",
  "game",
  "screenshots",
  "runtimes",
]);

export const CATEGORY_LABELS = Object.freeze({
  all: "All",
  browser: "Browsers",
  development: "Developer Tools",
  documents: "Office",
  communication: "Communication",
  utilities: "Utilities",
  security: "Security",
  productivity: "Productivity",
  cloud_storage: "Cloud Storage",
  collaboration: "Collaboration",
  entertainment: "Entertainment",
  photo: "Photos",
  game: "Games",
  screenshots: "Screenshots",
  runtimes: "Runtimes",
});

export const CATEGORY_ICONS = Object.freeze({
  all: FiGrid,
  browser: FiGlobe,
  development: FiCode,
  documents: FiFileText,
  communication: FiMessageCircle,
  utilities: FiTool,
  security: FiShield,
  productivity: FiCheckSquare,
  cloud_storage: FiCloud,
  collaboration: FiUsers,
  entertainment: FiFilm,
  photo: FiImage,
  game: FiTarget,
  screenshots: FiCrop,
  runtimes: FiCpu,
});

export const TOP_CATEGORY_SLUGS = Object.freeze([
  "browser",
  "development",
  "documents",
  "communication",
  "utilities",
]);
